name = "weather-hono-do-alarm"
main = "src/index.ts"
compatibility_date = "2026-09-01"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[durable_objects.bindings]]
name = "SLOT_DO"
class_name = "SlotScheduler"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SlotScheduler"]

[triggers]
crons = ["5 22 * * *", "5 9 * * *"]

[vars]
APP_ENV = "prod"
QWEATHER_API_HOST = "mx3yfu7e7k.re.qweatherapi.com"
CITY_NAME = "广州·海珠琶洲"
CITY_LOCATION = "101280108"
CITY_COORDS = "113.384,23.101"
PUBLIC_BASE_URL = "https://weather-card.20250101.ggff.net"
WECOM_SKIP_SEND = "0"
FORCE_HOURLY_RUN = "0"

[[kv_namespaces]]
binding = "ASSETS"
id = "62f5dfe0a95a468d81e0355bbad9a614"
